steps:
  # build and test project
  - name: 'oracle/graalvm-ce:20.0.0-java11'
    args: ['./gradlew', 'clean', 'build']
  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/micronaut-rest', '.' ]
  # deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'MicronautRest', '--image', 'gcr.io/$PROJECT_ID/latest', '--region', 'asia-east1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/micronaut-rest'
options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: 100